### PR TITLE
Update 0201extForm.tex

### PR DESCRIPTION
**Pull request by manjahdani**

### CODE REVIEW

**Comment by blegat** [comment]
cc @gauthmug

**Comment by blegat** [comment]
Makes sense indeed !

**Comment by gauthmug** [comment]
I agree !

**Comment by gauthmug** [comment]
How can I use the Terminal to make sure that my file in Atom gets synced too? 
I have tried
`git pull`
but it didn't work, i.e., I received the message 

> Already up-to-date.

which is not true...

**Comment by blegat** [comment]
This does not make sense. If atom is opening the files in the folder synced
by git then it should sync. Note that Atom 1.18 has added Github support
and better Git support.

**Comment by gauthmug** [comment]
I am almost sure that Atom is opening the files in the folder synced by git. How can I check? For example, I would also like to see the files added by the other students in my Atom editor, which I cannot see right now

**Comment by gauthmug** [comment]
I have found a solution, thanks to @mahanot 
I had to write 
`git pull upstream master`
instead of 
`git pull`

Thanks Maxime ! :)

**Pull request merged**
